# Generated by Django 4.2.2 on 2023-06-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_operational", models.BooleanField(default=True)),
                ("is_selected", models.BooleanField(default=False)),
                ("is_running", models.BooleanField(default=False)),
                ("direction", models.BooleanField(default=True)),
            ],
        ),
    ]
