# Generated by Django 4.2.2 on 2023-06-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevator",
            name="lift_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="elevator",
            name="on_floor",
            field=models.IntegerField(default=0),
        ),
    ]
