# Generated by Django 4.2.2 on 2023-06-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_elevator_lift_number_elevator_on_floor"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevator",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
    ]
