# Generated by Django 4.2.2 on 2023-06-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_elevator_is_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevator",
            name="dest_list",
            field=models.CharField(default="", max_length=200),
        ),
    ]
