# Generated by Django 4.2.2 on 2023-06-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_elevator_dest_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elevator",
            name="dest_list",
            field=models.CharField(default="[]", max_length=200),
        ),
    ]
