# Generated by Django 4.2.2 on 2023-06-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_elevator_dest_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elevator",
            old_name="lift_number",
            new_name="curr_floor",
        ),
        migrations.RenameField(
            model_name="elevator",
            old_name="on_floor",
            new_name="elevator_no",
        ),
        migrations.RenameField(
            model_name="elevator",
            old_name="is_operational",
            new_name="operational",
        ),
        migrations.RemoveField(
            model_name="elevator",
            name="is_open",
        ),
        migrations.RemoveField(
            model_name="elevator",
            name="is_running",
        ),
        migrations.RemoveField(
            model_name="elevator",
            name="is_selected",
        ),
        migrations.AddField(
            model_name="elevator",
            name="door",
            field=models.CharField(default="Closed", max_length=10),
        ),
        migrations.AddField(
            model_name="elevator",
            name="running",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="elevator",
            name="direction",
            field=models.CharField(default="Up", max_length=10),
        ),
    ]
