# Generated by Django 4.2.2 on 2023-06-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_rename_lift_number_elevator_curr_floor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevator",
            name="dest_waiting",
            field=models.CharField(default="[]", max_length=200),
        ),
        migrations.AlterField(
            model_name="elevator",
            name="elevator_no",
            field=models.IntegerField(),
        ),
    ]
