# Generated by Django 4.2.2 on 2023-06-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_elevator_dest_waiting_alter_elevator_elevator_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="elevator",
            name="max_floor",
            field=models.IntegerField(default=0),
        ),
    ]
